# Generated by Django 4.2.1 on 2023-05-23 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animals.category'),
        ),
        migrations.AlterField(
            model_name='card',
            name='animal',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='animals.animal'),
        ),
    ]
